import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import '../../models/purchase.dart';

class AddPurchaseScreen extends StatefulWidget {
  const AddPurchaseScreen({super.key});

  @override
  State<AddPurchaseScreen> createState() => _AddPurchaseScreenState();
}

class _AddPurchaseScreenState extends State<AddPurchaseScreen> {
  DateTime _selectedDate = DateTime.now();
  String? _selectedSupplierId;
  String? _selectedSupplierName;

  // Purchase Invoice Number
  String _invoiceNumber = '';
  final TextEditingController _invoiceController = TextEditingController();
  bool _isInvoiceAutoGenerated = true;

  // Cart items
  List<CartItem> _cartItems = [];

  // Single product selection
  String? _selectedProductId;
  String? _selectedProductName;
  final TextEditingController _purchaseRateController = TextEditingController();
  final TextEditingController _quantityController = TextEditingController();

  // Rounding amount
  final TextEditingController _roundingController = TextEditingController(
    text: '0',
  );
  double _roundingAmount = 0;

  bool _isLoading = false;
  double _productRate = 0;
  double _productSaleRate = 0;
  int _productGst = 18;

  List<QueryDocumentSnapshot> _suppliers = [];
  List<QueryDocumentSnapshot> _products = [];

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  @override
  void initState() {
    super.initState();
    _loadSuppliers();
    _loadProducts();
    _generateInvoiceNumber();
    _roundingController.addListener(_updateRounding);
  }

  void _updateRounding() {
    setState(() {
      _roundingAmount = double.tryParse(_roundingController.text) ?? 0;
    });
  }

  // Generate Invoice Number: INV-YYYYMMDD-XXX
  Future<void> _generateInvoiceNumber() async {
    try {
      String datePrefix = DateFormat('yyyyMMdd').format(DateTime.now());

      // Get count of purchases for today
      QuerySnapshot todayPurchases = await _firestore
          .collection('purchases')
          .where(
            'date',
            isGreaterThanOrEqualTo: Timestamp.fromDate(
              DateTime(
                DateTime.now().year,
                DateTime.now().month,
                DateTime.now().day,
              ),
            ),
          )
          .where(
            'date',
            isLessThan: Timestamp.fromDate(
              DateTime(
                DateTime.now().year,
                DateTime.now().month,
                DateTime.now().day + 1,
              ),
            ),
          )
          .get();

      int count = todayPurchases.docs.length + 1;
      String counter = count.toString().padLeft(3, '0');

      setState(() {
        _invoiceNumber = 'INV-$datePrefix-$counter';
        _invoiceController.text = _invoiceNumber;
      });
    } catch (e) {
      // Fallback: Generate based on timestamp
      String timestamp = DateTime.now().millisecondsSinceEpoch
          .toString()
          .substring(8);
      setState(() {
        _invoiceNumber =
            'INV-${DateFormat('yyyyMMdd').format(DateTime.now())}-$timestamp';
        _invoiceController.text = _invoiceNumber;
      });
    }
  }

  void _showDialog(String title, String message, {bool isError = false}) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          title: Row(
            children: [
              Icon(
                isError ? Icons.error_outline : Icons.check_circle_outline,
                color: isError ? Colors.red : Colors.green,
                size: 22,
              ),
              const SizedBox(width: 8),
              Text(
                title,
                style: const TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 15,
                ),
              ),
            ],
          ),
          content: Text(message, style: const TextStyle(fontSize: 13)),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              style: TextButton.styleFrom(foregroundColor: Colors.green[700]),
              child: const Text('OK', style: TextStyle(fontSize: 13)),
            ),
          ],
        );
      },
    );
  }

  Future<void> _loadSuppliers() async {
    try {
      QuerySnapshot snapshot = await _firestore.collection('suppliers').get();
      setState(() => _suppliers = snapshot.docs);
    } catch (e) {
      _showDialog('Error', 'Error loading suppliers: $e', isError: true);
    }
  }

  Future<void> _loadProducts() async {
    try {
      QuerySnapshot snapshot = await _firestore.collection('products').get();
      setState(() => _products = snapshot.docs);
    } catch (e) {
      _showDialog('Error', 'Error loading products: $e', isError: true);
    }
  }

  void _onProductSelected(String? productId) {
    if (productId == null) return;

    try {
      final product = _products.firstWhere((doc) => doc.id == productId);
      final productData = product.data() as Map<String, dynamic>;

      setState(() {
        _selectedProductId = productId;
        _selectedProductName = (productData['productName'] ?? 'Unknown')
            .toString();
        _productRate = (productData['purchaseRate'] ?? 0).toDouble();
        _productSaleRate = (productData['saleRate'] ?? 0).toDouble();
        _productGst = (productData['gstPercentage'] ?? 18).toInt();
        _purchaseRateController.text = _productRate.toString();
        _quantityController.text = '1';
      });
    } catch (e) {
      _showDialog('Error', 'Error selecting product: $e', isError: true);
    }
  }

  void _addToCart() {
    if (_selectedProductId == null) {
      _showDialog('Error', 'Please select a product', isError: true);
      return;
    }

    if (_quantityController.text.trim().isEmpty) {
      _showDialog('Error', 'Please enter quantity', isError: true);
      return;
    }

    int quantity = int.tryParse(_quantityController.text.trim()) ?? 0;
    if (quantity <= 0) {
      _showDialog('Error', 'Please enter valid quantity', isError: true);
      return;
    }

    double rate = double.tryParse(_purchaseRateController.text.trim()) ?? 0;
    if (rate <= 0) {
      _showDialog('Error', 'Please enter valid purchase rate', isError: true);
      return;
    }

    int existingIndex = _cartItems.indexWhere(
      (item) => item.productId == _selectedProductId,
    );

    if (existingIndex != -1) {
      setState(() {
        _cartItems[existingIndex].quantity += quantity;
        _cartItems[existingIndex].total =
            _cartItems[existingIndex].rate * _cartItems[existingIndex].quantity;
      });
      _showDialog('Success', 'Product quantity updated in cart!');
    } else {
      setState(() {
        _cartItems.add(
          CartItem(
            productId: _selectedProductId!,
            productName: _selectedProductName!,
            rate: rate,
            quantity: quantity,
            total: rate * quantity,
            gstPercentage: _productGst,
          ),
        );
      });
      _showDialog('Success', 'Product added to cart!');
    }

    setState(() {
      _selectedProductId = null;
      _selectedProductName = null;
      _purchaseRateController.clear();
      _quantityController.clear();
      _productRate = 0;
      _productSaleRate = 0;
      _productGst = 18;
    });
  }

  void _removeFromCart(int index) {
    setState(() => _cartItems.removeAt(index));
    _showDialog('Success', 'Product removed from cart');
  }

  void _updateCartItemQuantity(int index, int newQuantity) {
    if (newQuantity <= 0) {
      _removeFromCart(index);
      return;
    }

    setState(() {
      _cartItems[index].quantity = newQuantity;
      _cartItems[index].total = _cartItems[index].rate * newQuantity;
    });
  }

  double _getSubtotal() => _cartItems.fold(0, (sum, item) => sum + item.total);
  double _getTotalGST() => _cartItems.fold(
    0,
    (sum, item) => sum + (item.total * item.gstPercentage / 100),
  );
  double _getGrandTotal() => _getSubtotal() + _getTotalGST() + _roundingAmount;

  Future<void> _savePurchase() async {
    if (_selectedSupplierId == null || _selectedSupplierId!.isEmpty) {
      _showDialog(
        'Validation Error',
        'Please select a supplier',
        isError: true,
      );
      return;
    }

    if (_cartItems.isEmpty) {
      _showDialog(
        'Validation Error',
        'Please add at least one product to cart',
        isError: true,
      );
      return;
    }

    // Validate invoice number
    if (_invoiceController.text.trim().isEmpty) {
      _showDialog(
        'Validation Error',
        'Please enter an invoice number',
        isError: true,
      );
      return;
    }

    // Check if invoice number already exists
    try {
      QuerySnapshot existingInvoice = await _firestore
          .collection('purchases')
          .where('invoiceNo', isEqualTo: _invoiceController.text.trim())
          .get();

      if (existingInvoice.docs.isNotEmpty) {
        _showDialog(
          'Validation Error',
          'Invoice number ${_invoiceController.text.trim()} already exists. Please use a different number.',
          isError: true,
        );
        return;
      }
    } catch (e) {
      // Continue with save if check fails
    }

    setState(() => _isLoading = true);

    try {
      // Create PurchaseItem objects using the updated model
      List<PurchaseItem> purchaseItems = _cartItems
          .map(
            (item) => PurchaseItem(
              productId: item.productId,
              productName: item.productName,
              rate: item.rate, // Using 'rate' as per updated model
              quantity: item.quantity,
              total: item.total,
              gstPercentage: item.gstPercentage,
            ),
          )
          .toList();

      await _firestore.collection('purchases').add({
        'supplierId': _selectedSupplierId,
        'supplierName': _selectedSupplierName ?? 'Unknown',
        'invoiceNo': _invoiceController.text.trim(),
        'date': Timestamp.fromDate(_selectedDate),
        'items': purchaseItems.map((item) => item.toMap()).toList(),
        'totalAmount': _getSubtotal(),
        'gstAmount': _getTotalGST(),
        'roundingAmount': _roundingAmount,
        'grandTotal': _getGrandTotal(),
        'createdAt': FieldValue.serverTimestamp(),
      });

      setState(() {
        _selectedSupplierId = null;
        _selectedSupplierName = null;
        _cartItems.clear();
        _selectedProductId = null;
        _selectedProductName = null;
        _quantityController.clear();
        _purchaseRateController.clear();
        _selectedDate = DateTime.now();
        _productRate = 0;
        _productSaleRate = 0;
        _productGst = 18;
        _roundingController.text = '0';
        _roundingAmount = 0;
      });

      // Generate new invoice number for next purchase
      await _generateInvoiceNumber();

      _showDialog('Success', 'Purchase added successfully!');
    } catch (e) {
      _showDialog(
        'Error',
        'Error saving purchase: ${e.toString()}',
        isError: true,
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        bool isMobile = constraints.maxWidth < 800;

        return Container(
          color: Colors.grey[50],
          padding: EdgeInsets.all(isMobile ? 12 : 20),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildHeader(isMobile),
                const SizedBox(height: 16),
                if (isMobile) _buildMobileLayout() else _buildDesktopLayout(),
                const SizedBox(height: 16),
                _buildSubmitButton(),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildHeader(bool isMobile) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [Colors.green[400]!, Colors.green[700]!],
              ),
              borderRadius: BorderRadius.circular(10),
            ),
            child: const Icon(
              Icons.shopping_cart_checkout,
              color: Colors.white,
              size: 20,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Add New Purchase',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.green,
                  ),
                ),
                Text(
                  'Add multiple products in one purchase',
                  style: TextStyle(fontSize: 10, color: Colors.grey[600]),
                ),
              ],
            ),
          ),
          if (!isMobile)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
              decoration: BoxDecoration(
                color: Colors.green[50],
                borderRadius: BorderRadius.circular(16),
              ),
              child: Text(
                'Items: ${_cartItems.length}',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                  color: Colors.green[700],
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildDesktopLayout() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(flex: 2, child: _buildFormSection()),
        const SizedBox(width: 16),
        Expanded(flex: 1, child: _buildCartSection()),
      ],
    );
  }

  Widget _buildMobileLayout() {
    return Column(
      children: [
        _buildFormSection(),
        const SizedBox(height: 16),
        _buildCartSection(),
      ],
    );
  }

  Widget _buildFormSection() {
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Invoice Number Section
            _buildSectionHeader(
              Icons.receipt,
              'Invoice Number',
              'Unique invoice identifier',
            ),
            const SizedBox(height: 10),
            _buildInvoiceNumberField(),
            const SizedBox(height: 16),

            _buildSectionHeader(
              Icons.calendar_today,
              'Purchase Date',
              'Select purchase date',
            ),
            const SizedBox(height: 10),
            _buildDateSelector(),
            const SizedBox(height: 16),

            _buildSectionHeader(
              Icons.business,
              'Supplier Information',
              'Select supplier',
            ),
            const SizedBox(height: 10),
            _buildSupplierDropdown(),
            const SizedBox(height: 20),

            _buildSectionHeader(
              Icons.add_shopping_cart,
              'Add Products',
              'Select product and add to cart',
            ),
            const SizedBox(height: 16),
            _buildProductSelector(),
          ],
        ),
      ),
    );
  }

  Widget _buildInvoiceNumberField() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 2),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.grey[300]!),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        children: [
          Icon(Icons.receipt_long, color: Colors.green[700], size: 16),
          const SizedBox(width: 8),
          Expanded(
            child: TextField(
              controller: _invoiceController,
              style: const TextStyle(fontSize: 13),
              decoration: const InputDecoration(
                hintText: 'Enter invoice number',
                hintStyle: TextStyle(fontSize: 12),
                border: InputBorder.none,
                isDense: true,
                contentPadding: EdgeInsets.symmetric(vertical: 8),
              ),
              onChanged: (value) {
                setState(() {
                  _isInvoiceAutoGenerated = false;
                });
              },
            ),
          ),
          if (_isInvoiceAutoGenerated)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
              decoration: BoxDecoration(
                color: Colors.green[50],
                borderRadius: BorderRadius.circular(5),
              ),
              child: Text(
                'Auto',
                style: TextStyle(
                  fontSize: 9,
                  color: Colors.green[700],
                  fontWeight: FontWeight.w500,
                ),
              ),
            ),
          IconButton(
            onPressed: () async {
              await _generateInvoiceNumber();
              setState(() {
                _isInvoiceAutoGenerated = true;
              });
            },
            icon: Icon(Icons.refresh, size: 18, color: Colors.green[700]),
            padding: EdgeInsets.zero,
            constraints: const BoxConstraints(),
            tooltip: 'Generate new invoice number',
          ),
        ],
      ),
    );
  }

  Widget _buildDateSelector() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 2),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.grey[300]!),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        children: [
          Icon(Icons.calendar_today, color: Colors.green[700], size: 16),
          const SizedBox(width: 8),
          const Text(
            'Date:',
            style: TextStyle(fontSize: 12, fontWeight: FontWeight.w500),
          ),
          const SizedBox(width: 8),
          TextButton(
            onPressed: () async {
              DateTime? picked = await showDatePicker(
                context: context,
                initialDate: _selectedDate,
                firstDate: DateTime(2020),
                lastDate: DateTime.now(),
              );
              if (picked != null) setState(() => _selectedDate = picked);
            },
            child: Text(
              '${_selectedDate.day}/${_selectedDate.month}/${_selectedDate.year}',
              style: const TextStyle(fontSize: 12),
            ),
          ),
          const Spacer(),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
            decoration: BoxDecoration(
              color: Colors.green[50],
              borderRadius: BorderRadius.circular(5),
            ),
            child: Text(
              'Today: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
              style: TextStyle(fontSize: 9, color: Colors.green[700]),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSupplierDropdown() {
    return DropdownButtonFormField<String>(
      decoration: _buildInputDecoration('Select Supplier *', Icons.business),
      value: _selectedSupplierId,
      items: _suppliers.map((supplier) {
        Map<String, dynamic> data = supplier.data() as Map<String, dynamic>;
        return DropdownMenuItem(
          value: supplier.id,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                data['name'] ?? 'Unknown',
                style: const TextStyle(fontSize: 12),
              ),
              if (data['gstNumber'] != null &&
                  data['gstNumber'].toString().isNotEmpty)
                Text(
                  'GST: ${data['gstNumber']}',
                  style: const TextStyle(fontSize: 10, color: Colors.grey),
                ),
            ],
          ),
        );
      }).toList(),
      onChanged: (value) {
        if (value != null) {
          final supplier = _suppliers.firstWhere((doc) => doc.id == value);
          Map<String, dynamic> data = supplier.data() as Map<String, dynamic>;
          setState(() {
            _selectedSupplierId = value;
            _selectedSupplierName = (data['name'] ?? 'Unknown').toString();
          });
        }
      },
      validator: (value) => value == null ? 'Please select a supplier' : null,
    );
  }

  Widget _buildProductSelector() {
    return Column(
      children: [
        DropdownButtonFormField<String>(
          decoration: _buildInputDecoration(
            'Select Product *',
            Icons.shopping_cart,
          ),
          value: _selectedProductId,
          items: _products.map((product) {
            Map<String, dynamic> data = product.data() as Map<String, dynamic>;
            return DropdownMenuItem(
              value: product.id,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '${data['productName'] ?? 'Unknown'} (${data['productType'] ?? 'N/A'})',
                    style: const TextStyle(fontSize: 12),
                  ),
                ],
              ),
            );
          }).toList(),
          onChanged: _onProductSelected,
        ),
        const SizedBox(height: 10),

        if (_selectedProductId != null) ...[
          Row(
            children: [
              Expanded(
                child: TextFormField(
                  controller: _purchaseRateController,
                  decoration: _buildInputDecoration(
                    'Purchase Rate',
                    Icons.currency_rupee,
                    suffix: '₹',
                  ),
                  keyboardType: TextInputType.number,
                  style: const TextStyle(fontSize: 12),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: TextFormField(
                  controller: _quantityController,
                  decoration: _buildInputDecoration(
                    'Quantity',
                    Icons.numbers,
                    suffix: 'units',
                  ),
                  keyboardType: TextInputType.number,
                  style: const TextStyle(fontSize: 12),
                ),
              ),
              const SizedBox(width: 10),
              ElevatedButton.icon(
                onPressed: _addToCart,
                icon: const Icon(Icons.add_shopping_cart, size: 16),
                label: const Text('Add', style: TextStyle(fontSize: 12)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.green[700],
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 10,
                  ),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
              ),
            ],
          ),
          if (_productSaleRate > 0)
            Container(
              margin: const EdgeInsets.only(top: 8),
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: Colors.green[50],
                borderRadius: BorderRadius.circular(6),
              ),
              child: Text(
                'Suggested Sale Rate: ₹${_productSaleRate.toStringAsFixed(2)}',
                style: TextStyle(fontSize: 10, color: Colors.green[700]),
              ),
            ),
        ],
      ],
    );
  }

  Widget _buildCartSection() {
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: Column(
        children: [
          Container(
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: Colors.green[50],
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(14),
                topRight: Radius.circular(14),
              ),
            ),
            child: Row(
              children: [
                Icon(Icons.shopping_cart, color: Colors.green[700], size: 18),
                const SizedBox(width: 6),
                Text(
                  'Cart (${_cartItems.length} items)',
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                    color: Colors.green[800],
                  ),
                ),
              ],
            ),
          ),

          if (_cartItems.isEmpty)
            Container(
              padding: const EdgeInsets.all(30),
              child: Column(
                children: [
                  Icon(Icons.shopping_cart, size: 50, color: Colors.grey[400]),
                  const SizedBox(height: 8),
                  Text(
                    'Cart is empty',
                    style: TextStyle(fontSize: 13, color: Colors.grey[600]),
                  ),
                  Text(
                    'Add products from above',
                    style: TextStyle(fontSize: 11, color: Colors.grey[500]),
                  ),
                ],
              ),
            )
          else
            Column(
              children: [
                ConstrainedBox(
                  constraints: const BoxConstraints(maxHeight: 300),
                  child: ListView.builder(
                    shrinkWrap: true,
                    itemCount: _cartItems.length,
                    itemBuilder: (context, index) {
                      final item = _cartItems[index];
                      return _buildCartItemCard(item, index);
                    },
                  ),
                ),
                const Divider(),
                Container(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    children: [
                      _buildCartSummaryRow('Subtotal:', _getSubtotal()),
                      _buildCartSummaryRow('GST:', _getTotalGST()),
                      _buildRoundingField(),
                      const Divider(),
                      _buildCartSummaryRow(
                        'Grand Total:',
                        _getGrandTotal(),
                        isBold: true,
                      ),
                    ],
                  ),
                ),
              ],
            ),
        ],
      ),
    );
  }

  Widget _buildRoundingField() {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          const Text('Rounding:', style: TextStyle(fontSize: 12)),
          Container(
            width: 120,
            height: 35,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.grey[300]!),
              borderRadius: BorderRadius.circular(6),
            ),
            child: Row(
              children: [
                IconButton(
                  onPressed: () {
                    double current =
                        double.tryParse(_roundingController.text) ?? 0;
                    setState(() {
                      _roundingController.text = (current - 1).toString();
                      _roundingAmount = current - 1;
                    });
                  },
                  icon: const Icon(Icons.remove, size: 16),
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                ),
                Expanded(
                  child: TextField(
                    controller: _roundingController,
                    textAlign: TextAlign.center,
                    style: const TextStyle(fontSize: 12),
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(
                      border: InputBorder.none,
                      isDense: true,
                      contentPadding: EdgeInsets.symmetric(vertical: 4),
                    ),
                  ),
                ),
                IconButton(
                  onPressed: () {
                    double current =
                        double.tryParse(_roundingController.text) ?? 0;
                    setState(() {
                      _roundingController.text = (current + 1).toString();
                      _roundingAmount = current + 1;
                    });
                  },
                  icon: const Icon(Icons.add, size: 16),
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCartItemCard(CartItem item, int index) {
    return Card(
      margin: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10),
        side: BorderSide(color: Colors.grey[200]!),
      ),
      child: Container(
        padding: const EdgeInsets.all(10),
        child: Row(
          children: [
            Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: Colors.green[50],
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(
                Icons.shopping_bag,
                color: Colors.green[700],
                size: 20,
              ),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    item.productName,
                    style: const TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w500,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 2),
                  Text(
                    'Rate: ₹${item.rate.toStringAsFixed(2)} | GST: ${item.gstPercentage}%',
                    style: TextStyle(fontSize: 10, color: Colors.grey[600]),
                  ),
                ],
              ),
            ),
            Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Text(
                  '₹${item.total.toStringAsFixed(2)}',
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                    color: Colors.green,
                  ),
                ),
                const SizedBox(height: 6),
                Row(
                  children: [
                    Container(
                      decoration: BoxDecoration(
                        border: Border.all(color: Colors.grey[300]!),
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: Row(
                        children: [
                          IconButton(
                            onPressed: () => _updateCartItemQuantity(
                              index,
                              item.quantity - 1,
                            ),
                            icon: const Icon(Icons.remove, size: 14),
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                            splashRadius: 16,
                          ),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 6),
                            child: Text(
                              item.quantity.toString(),
                              style: const TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                          IconButton(
                            onPressed: () => _updateCartItemQuantity(
                              index,
                              item.quantity + 1,
                            ),
                            icon: const Icon(Icons.add, size: 14),
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                            splashRadius: 16,
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 6),
                    IconButton(
                      onPressed: () => _removeFromCart(index),
                      icon: const Icon(
                        Icons.delete_outline,
                        size: 18,
                        color: Colors.red,
                      ),
                      padding: EdgeInsets.zero,
                      constraints: const BoxConstraints(),
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSubmitButton() {
    return SizedBox(
      width: double.infinity,
      child: ElevatedButton(
        onPressed: _isLoading || _cartItems.isEmpty ? null : _savePurchase,
        style: ElevatedButton.styleFrom(
          padding: const EdgeInsets.symmetric(vertical: 12),
          backgroundColor: Colors.green[700],
          foregroundColor: Colors.white,
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
        ),
        child: _isLoading
            ? const SizedBox(
                height: 18,
                width: 18,
                child: CircularProgressIndicator(
                  color: Colors.white,
                  strokeWidth: 2,
                ),
              )
            : const Text(
                'Complete Purchase',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
              ),
      ),
    );
  }

  Widget _buildSectionHeader(IconData icon, String title, String subtitle) {
    return Row(
      children: [
        Container(
          padding: const EdgeInsets.all(5),
          decoration: BoxDecoration(
            color: Colors.green[50],
            borderRadius: BorderRadius.circular(7),
          ),
          child: Icon(icon, color: Colors.green[700], size: 14),
        ),
        const SizedBox(width: 6),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
            ),
            Text(
              subtitle,
              style: TextStyle(fontSize: 9, color: Colors.grey[600]),
            ),
          ],
        ),
      ],
    );
  }

  InputDecoration _buildInputDecoration(
    String label,
    IconData icon, {
    String? suffix,
  }) {
    return InputDecoration(
      labelText: label,
      labelStyle: const TextStyle(fontSize: 11),
      hintText: 'Enter $label',
      hintStyle: const TextStyle(fontSize: 10),
      suffixText: suffix,
      prefixIcon: Icon(icon, size: 16, color: Colors.green[600]),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: Colors.grey[300]!),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: Colors.grey[300]!),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: BorderSide(color: Colors.green[700]!, width: 1.5),
      ),
      contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 10),
      isDense: true,
    );
  }

  Widget _buildCartSummaryRow(
    String label,
    double value, {
    bool isBold = false,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: TextStyle(
              fontSize: isBold ? 13 : 12,
              fontWeight: isBold ? FontWeight.bold : FontWeight.normal,
            ),
          ),
          Text(
            '₹${value.toStringAsFixed(2)}',
            style: TextStyle(
              fontSize: isBold ? 13 : 12,
              fontWeight: isBold ? FontWeight.bold : FontWeight.normal,
              color: isBold ? Colors.green[700] : Colors.black,
            ),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _invoiceController.dispose();
    _purchaseRateController.dispose();
    _quantityController.dispose();
    _roundingController.removeListener(_updateRounding);
    _roundingController.dispose();
    super.dispose();
  }
}

// Cart Item Model
class CartItem {
  String productId;
  String productName;
  double rate;
  int quantity;
  double total;
  int gstPercentage;

  CartItem({
    required this.productId,
    required this.productName,
    required this.rate,
    required this.quantity,
    required this.total,
    required this.gstPercentage,
  });
}
